version: 2

multi-ecosystem-groups:
  application:
    schedule:
      interval: "monthly"
  documentation:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "application"

  - package-ecosystem: "pip"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "application"

  - package-ecosystem: "npm"
    directory: "/web"
    patterns: ["*"]
    multi-ecosystem-group: "application"

  - package-ecosystem: "npm"
    directory: "/docs"
    patterns: ["*"]
    multi-ecosystem-group: "documentation"
